name: CI - Dog API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        run: mvn -B -ntp clean test

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report
        continue-on-error: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.run_number }}
          path: |
            target/surefire-reports/
            target/allure-results/
            target/site/allure-maven-plugin/
          retention-days: 30
          
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests Results
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false