name: CI/CD - Dog API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Permissões necessárias para o workflow
permissions:
  contents: read
  pages: write
  id-token: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Run tests
        run: mvn -B -ntp clean test

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report
        continue-on-error: true

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports-${{ github.run_number }}
          path: target/surefire-reports
          retention-days: 30

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ github.run_number }}
          path: target/allure-results
          retention-days: 30

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-${{ github.run_number }}
          path: target/site/allure-maven-plugin/
          retention-days: 30

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Run OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check -Dformat=HTML
      continue-on-error: true
      
    - name: Upload Security Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-report-${{ github.run_number }}
        path: target/dependency-check-report.html
        retention-days: 30

  deploy-reports:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    # Permissões específicas para este job
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Allure Report
      uses: actions/download-artifact@v4
      with:
        name: allure-report-${{ github.run_number }}
        path: allure-report
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages